/* =========================================================
   中学英語（中1〜中3）の データ
   g: 9=中1, 10=中2, 11=中3
   grammar: 文法の あなうめ { s: ___ を ふくむ文, a: 正解, d: まちがい, ja: 意味 }
   ========================================================= */
window.JH = (function () {
  const G = (g, s, a, d, ja) => ({ g, s, a, d, ja });
  const grammar = [
    // ---- 中1：be動詞・一般動詞・三単現・進行形・過去形・can・命令文・疑問詞 ----
    G(9, 'I ___ a student.', 'am', ['is', 'are', 'be'], 'わたしは生徒です。'),
    G(9, 'They ___ my friends.', 'are', ['is', 'am', 'be'], 'かれらはわたしの友だちです。'),
    G(9, 'She ___ tennis every day.', 'plays', ['play', 'playing', 'to play'], '彼女は毎日テニスをします。'),
    G(9, '___ you like music?', 'Do', ['Does', 'Are', 'Is'], 'あなたは音楽が好きですか。'),
    G(9, '___ he live in Osaka?', 'Does', ['Do', 'Is', 'Are'], '彼は大阪に住んでいますか。'),
    G(9, 'I ___ not like carrots.', 'do', ['does', 'am', 'is'], 'わたしはにんじんが好きではありません。'),
    G(9, 'My mother ___ breakfast every morning.', 'makes', ['make', 'making', 'to make'], '母は毎朝朝食を作ります。'),
    G(9, 'He is ___ a book now.', 'reading', ['read', 'reads', 'to read'], '彼は今、本を読んでいます。'),
    G(9, 'What are you ___ now?', 'doing', ['do', 'does', 'did'], 'あなたは今、何をしていますか。'),
    G(9, 'I ___ to the zoo yesterday.', 'went', ['go', 'goes', 'going'], 'わたしはきのう動物園に行きました。'),
    G(9, 'We ___ soccer last Sunday.', 'played', ['play', 'plays', 'playing'], 'わたしたちはこの前の日曜日にサッカーをしました。'),
    G(9, 'Did you ___ the movie?', 'see', ['saw', 'seen', 'sees'], 'あなたはその映画を見ましたか。'),
    G(9, 'This is ___ bag.', 'my', ['I', 'me', 'mine'], 'これはわたしのかばんです。'),
    G(9, 'I know ___ well.', 'him', ['he', 'his', 'they'], 'わたしは彼をよく知っています。'),
    G(9, '___ is that girl? — She is Emi.', 'Who', ['What', 'Where', 'When'], 'あの女の子はだれですか。— エミです。'),
    G(9, '___ do you go to school? — By bus.', 'How', ['What', 'Who', 'Which'], 'どうやって学校に行きますか。— バスで。'),
    G(9, 'I can ___ the guitar.', 'play', ['plays', 'playing', 'played'], 'わたしはギターをひくことができます。'),
    G(9, '___ your hands before lunch.', 'Wash', ['Washing', 'Washes', 'Washed'], '昼食の前に手を洗いなさい。'),
    G(9, 'How many books ___ you have?', 'do', ['does', 'are', 'is'], 'あなたは本を何冊持っていますか。'),
    G(9, '___ was the weather yesterday? — It was sunny.', 'How', ['What', 'Who', 'Which'], 'きのうの天気はどうでしたか。— 晴れでした。'),
    // ---- 中2：未来・there is・比較・不定詞・動名詞・助動詞・接続詞・過去進行形 ----
    G(10, 'I ___ visit Kyoto next week.', 'will', ['was', 'did', 'am'], 'わたしは来週、京都を訪れます。'),
    G(10, 'She is going ___ buy a new bike.', 'to', ['for', 'at', 'in'], '彼女は新しい自転車を買うつもりです。'),
    G(10, 'It ___ rain tomorrow.', 'will', ['is', 'does', 'was'], '明日は雨がふるでしょう。'),
    G(10, 'There ___ many people in the park.', 'are', ['is', 'am', 'be'], '公園にはたくさんの人がいます。'),
    G(10, 'There ___ a cat under the table.', 'is', ['are', 'am', 'be'], 'テーブルの下にねこが1ぴきいます。'),
    G(10, 'Tom is ___ than Ken.', 'taller', ['tall', 'tallest', 'more tall'], 'トムはケンより背が高い。'),
    G(10, 'This is the ___ mountain in Japan.', 'highest', ['high', 'higher', 'most high'], 'これは日本でいちばん高い山です。'),
    G(10, 'This book is ___ interesting than that one.', 'more', ['most', 'very', 'much'], 'この本はあの本よりおもしろい。'),
    G(10, 'I like summer the ___ of all seasons.', 'best', ['better', 'good', 'well'], 'すべての季節の中で夏がいちばん好きです。'),
    G(10, 'He is the tallest ___ the three.', 'of', ['in', 'than', 'at'], '彼は3人の中でいちばん背が高い。'),
    G(10, 'I want ___ a doctor.', 'to be', ['be', 'being', 'am'], 'わたしは医者になりたいです。'),
    G(10, 'I enjoyed ___ soccer with my friends.', 'playing', ['play', 'to play', 'played'], '友だちとサッカーをして楽しみました。'),
    G(10, 'I finished ___ my homework.', 'doing', ['do', 'to do', 'did'], 'わたしは宿題をし終えました。'),
    G(10, 'You ___ to get up early tomorrow.', 'have', ['must', 'should', 'can'], 'あなたは明日早く起きなければなりません。'),
    G(10, 'You ___ run in the classroom.', 'must not', ['must', "don't have to", 'have to'], '教室で走ってはいけません。'),
    G(10, 'I went to the library ___ read books.', 'to', ['for', 'at', 'by'], 'わたしは本を読むために図書館へ行きました。'),
    G(10, 'I was ___ TV when he called me.', 'watching', ['watch', 'watched', 'watches'], '彼が電話してきたとき、わたしはテレビを見ていました。'),
    G(10, '___ it is sunny tomorrow, let\'s go hiking.', 'If', ['Because', 'But', 'So'], 'もし明日晴れたら、ハイキングに行こう。'),
    G(10, 'I stayed home ___ I had a cold.', 'because', ['if', 'but', 'so'], 'かぜをひいていたので、わたしは家にいました。'),
    G(10, 'Can you show me how ___ use this?', 'to', ['for', 'of', 'at'], 'これの使い方を教えてくれますか。'),
    G(10, 'He gave ___ a present.', 'me', ['I', 'my', 'mine'], '彼はわたしにプレゼントをくれました。'),
    G(10, 'Shall I ___ the window? — Yes, please.', 'open', ['opens', 'opened', 'opening'], '窓を開けましょうか。— はい、お願いします。'),
    // ---- 中3：現在完了・受け身・関係代名詞・分詞・間接疑問・不定詞の応用・仮定法 ----
    G(11, 'I have ___ in Tokyo for five years.', 'lived', ['live', 'living', 'lives'], 'わたしは5年間東京に住んでいます。'),
    G(11, 'Have you ever ___ to Okinawa?', 'been', ['went', 'go', 'going'], 'あなたは沖縄に行ったことがありますか。'),
    G(11, 'I have ___ finished my homework.', 'already', ['yet', 'ever', 'since'], 'わたしはもう宿題を終えました。'),
    G(11, 'I have known him ___ 2020.', 'since', ['for', 'ago', 'during'], 'わたしは2020年から彼を知っています。'),
    G(11, 'I have been ___ for two hours.', 'studying', ['study', 'studies', 'to study'], 'わたしは2時間ずっと勉強しています。'),
    G(11, 'This temple ___ built 300 years ago.', 'was', ['is', 'has', 'were'], 'この寺は300年前に建てられました。'),
    G(11, 'English is ___ in many countries.', 'spoken', ['speak', 'spoke', 'speaking'], '英語は多くの国で話されています。'),
    G(11, 'The letter ___ by Mary was long.', 'written', ['wrote', 'writes', 'writing'], 'メアリーによって書かれた手紙は長かった。'),
    G(11, 'The boy ___ is running there is my brother.', 'who', ['which', 'what', 'where'], 'あそこで走っている男の子はわたしの弟です。'),
    G(11, 'This is the book ___ I bought yesterday.', 'which', ['who', 'what', 'where'], 'これはわたしがきのう買った本です。'),
    G(11, 'The girl ___ with Ken is Yumi.', 'talking', ['talks', 'talked', 'to talk'], 'ケンと話している女の子はユミです。'),
    G(11, 'Look at the ___ window.', 'broken', ['break', 'broke', 'breaking'], 'われた窓を見て。'),
    G(11, 'Do you know where ___ ?', 'he lives', ['does he live', 'he live', 'lives he'], '彼がどこに住んでいるか知っていますか。'),
    G(11, 'It is important ___ study every day.', 'to', ['for', 'of', 'that'], '毎日勉強することは大切です。'),
    G(11, 'It is too hot ___ play outside.', 'to', ['for', 'that', 'so'], '外で遊ぶには暑すぎます。'),
    G(11, 'I want you ___ help me.', 'to', ['for', 'that', 'of'], 'わたしはあなたに手伝ってほしいです。'),
    G(11, 'My mother made me ___ my room.', 'clean', ['to clean', 'cleaning', 'cleaned'], '母はわたしに部屋をそうじさせました。'),
    G(11, 'This song makes me ___.', 'happy', ['happily', 'happiness', 'to happy'], 'この歌はわたしを幸せな気持ちにします。'),
    G(11, 'If I ___ a bird, I could fly.', 'were', ['am', 'is', 'be'], 'もしわたしが鳥なら、飛べるのに。'),
    G(11, 'I wish I ___ speak French.', 'could', ['can', 'will', 'am'], 'フランス語が話せたらいいのに。'),

    // ---- 中1 追加 ----
    G(9, 'Ken and I ___ good friends.', 'are', ['is', 'am', 'be'], 'ケンとわたしは仲のよい友だちです。'),
    G(9, '___ this your umbrella? — Yes, it is.', 'Is', ['Are', 'Do', 'Does'], 'これはあなたのかさですか。— はい。'),
    G(9, 'That ___ my school.', 'is', ['are', 'am', 'do'], 'あれはわたしの学校です。'),
    G(9, 'We ___ from Canada.', 'are', ['is', 'am', 'does'], 'わたしたちはカナダ出身です。'),
    G(9, 'I ___ a dog and two cats.', 'have', ['has', 'having', 'am'], 'わたしは犬1ぴきとねこ2ひきを飼っています。'),
    G(9, 'My sister ___ to music every night.', 'listens', ['listen', 'listening', 'is listen'], '姉（妹）は毎晩音楽を聞きます。'),
    G(9, 'Tom ___ not play tennis.', 'does', ['do', 'is', 'are'], 'トムはテニスをしません。'),
    G(9, '___ your father cook?', 'Does', ['Do', 'Is', 'Are'], 'お父さんは料理をしますか。'),
    G(9, 'She ___ English very well.', 'speaks', ['speak', 'speaking', 'is speak'], '彼女はとても上手に英語を話します。'),
    G(9, 'He ___ TV now.', 'is watching', ['watches', 'watch', 'watching'], '彼は今テレビを見ています。'),
    G(9, 'We ___ lunch at noon yesterday.', 'had', ['have', 'has', 'having'], 'わたしたちはきのう正午に昼食を食べました。'),
    G(9, 'She ___ to school by bus yesterday.', 'came', ['come', 'comes', 'coming'], '彼女はきのうバスで学校に来ました。'),
    G(9, 'I ___ not watch TV last night.', 'did', ['do', 'was', 'does'], 'わたしはきのうの夜テレビを見ませんでした。'),
    G(9, '___ you busy yesterday? — Yes, I was.', 'Were', ['Was', 'Did', 'Are'], 'きのうは忙しかったですか。— はい。'),
    G(9, 'It ___ cold this morning.', 'was', ['is', 'were', 'did'], '今朝は寒かった。'),
    G(9, 'Those are ___ books.', 'their', ['they', 'them', 'theirs'], 'あれらは彼らの本です。'),
    G(9, 'This bag is ___.', 'hers', ['she', 'her', 'hers\''], 'このかばんは彼女のものです。'),
    G(9, 'Please help ___.', 'us', ['we', 'our', 'ours'], 'わたしたちを手伝ってください。'),
    G(9, '___ is your birthday? — It is May 5th.', 'When', ['What', 'Where', 'Who'], 'たんじょうびはいつですか。— 5月5日です。'),
    G(9, '___ pen is this? — It is Mike\'s.', 'Whose', ['Who', 'Which', 'What'], 'これはだれのペンですか。— マイクのです。'),
    G(9, '___ time is it now? — It is ten.', 'What', ['How', 'When', 'Which'], '今何時ですか。— 10時です。'),
    G(9, '___ old is your brother?', 'How', ['What', 'When', 'Who'], 'お兄さんは何歳ですか。'),
    G(9, 'I can ___ fast.', 'swim', ['swims', 'swimming', 'swam'], 'わたしは速く泳げます。'),
    G(9, '___ you open the door, please?', 'Can', ['Are', 'Do', 'Is'], 'ドアを開けてくれますか。'),
    G(9, '___ be quiet, please.', 'Please', ['Do', 'Are', 'You'], '静かにしてください。'),
    G(9, '___ run in the hallway.', "Don't", ['Not', "Doesn't", "Isn't"], 'ろうかで走ってはいけません。'),
    G(9, "Let's ___ to the park.", 'go', ['goes', 'going', 'went'], '公園に行きましょう。'),
    G(9, 'There ___ a cat on the chair.', 'is', ['are', 'am', 'be'], 'いすの上にねこがいます。'),
    G(9, 'I get up ___ seven every day.', 'at', ['in', 'on', 'to'], 'わたしは毎日7時に起きます。'),
    G(9, 'We have a festival ___ August.', 'in', ['at', 'on', 'of'], '8月に祭りがあります。'),
    G(9, 'The cat is ___ the box.', 'in', ['at', 'to', 'of'], 'ねこは箱の中にいます。'),
    G(9, 'How many ___ do you have?', 'dogs', ['dog', 'a dog', 'dogs\''], '犬を何びき飼っていますか。'),
    // ---- 中2 追加 ----
    G(10, 'I ___ going to study tonight.', 'am', ['is', 'are', 'will'], 'わたしは今夜勉強するつもりです。'),
    G(10, 'She ___ be fifteen next year.', 'will', ['is', 'does', 'was'], '彼女は来年15歳になります。'),
    G(10, '___ you come to the party tomorrow?', 'Will', ['Are', 'Do', 'Did'], '明日パーティーに来ますか。'),
    G(10, 'I ___ not be late tomorrow.', 'will', ['am', 'do', 'did'], '明日はおくれません。'),
    G(10, 'There ___ a lot of stars last night.', 'were', ['was', 'is', 'are'], 'きのうの夜はたくさんの星がありました。'),
    G(10, 'Is there ___ water in the bottle?', 'any', ['some', 'many', 'a'], 'びんに水はありますか。'),
    G(10, 'I have ___ friends in Tokyo.', 'a few', ['a little', 'much', 'any'], '東京に友だちが何人かいます。'),
    G(10, 'How ___ money do you have?', 'much', ['many', 'old', 'long'], 'お金をいくら持っていますか。'),
    G(10, 'My bag is ___ than yours.', 'heavier', ['heavy', 'heaviest', 'more heavy'], 'わたしのかばんはあなたのより重い。'),
    G(10, 'This is the ___ movie of the year.', 'best', ['good', 'better', 'most good'], 'これは今年いちばんよい映画です。'),
    G(10, 'Ken runs ___ than I.', 'faster', ['fast', 'fastest', 'more fast'], 'ケンはわたしより速く走ります。'),
    G(10, 'She is as ___ as her mother.', 'tall', ['taller', 'tallest', 'more tall'], '彼女はお母さんと同じくらい背が高い。'),
    G(10, 'Which is ___, this one or that one?', 'bigger', ['big', 'biggest', 'more big'], 'これとあれ、どちらが大きいですか。'),
    G(10, 'This question is the ___ difficult of all.', 'most', ['more', 'very', 'much'], 'この問題はすべての中でいちばん難しい。'),
    G(10, 'I want ___ a new bike.', 'to buy', ['buy', 'buying', 'bought'], '新しい自転車を買いたいです。'),
    G(10, 'She went to Kyoto ___ see her aunt.', 'to', ['for', 'at', 'in'], '彼女はおばに会うために京都へ行きました。'),
    G(10, 'I have something ___ you.', 'to tell', ['tell', 'telling', 'told'], 'あなたに言いたいことがあります。'),
    G(10, 'It is important ___ read books.', 'to', ['for', 'of', 'that'], '本を読むことは大切です。'),
    G(10, 'He is good at ___.', 'swimming', ['swim', 'to swim', 'swims'], '彼は泳ぐのが得意です。'),
    G(10, 'Thank you for ___ me.', 'helping', ['help', 'to help', 'helped'], '手伝ってくれてありがとう。'),
    G(10, 'I like ___ pictures.', 'taking', ['take', 'took', 'takes'], 'わたしは写真をとるのが好きです。'),
    G(10, 'You ___ eat vegetables every day.', 'should', ['must not', 'may', 'could'], '毎日野菜を食べたほうがいいです。'),
    G(10, '___ I open the window?', 'May', ['Will', 'Do', 'Am'], '窓を開けてもいいですか。'),
    G(10, 'We ___ wear uniforms at school.', 'have to', ['has to', 'having to', 'had'], 'わたしたちは学校で制服を着なければなりません。'),
    G(10, 'You ___ have to come early.', "don't", ["doesn't", "aren't", "didn't"], '早く来なくてもいいです。'),
    G(10, 'I was ___ my homework at nine.', 'doing', ['do', 'did', 'does'], '9時に宿題をしていました。'),
    G(10, 'What ___ you doing then?', 'were', ['was', 'are', 'did'], 'そのとき何をしていましたか。'),
    G(10, 'I think ___ he is kind.', 'that', ['what', 'which', 'who'], '彼は親切だと思います。'),
    G(10, 'I was tired, ___ I went to bed early.', 'so', ['because', 'if', 'but'], 'つかれていたので早くねました。'),
    G(10, '___ I was a child, I lived in Nara.', 'When', ['If', 'Because', 'That'], '子どものころ、奈良に住んでいました。'),
    G(10, 'My father gave ___ to me.', 'this watch', ['me this watch', 'to this watch', 'this watch me'], '父はこの時計をわたしにくれました。'),
    G(10, 'She looks ___.', 'happy', ['happily', 'happiness', 'to happy'], '彼女は幸せそうに見えます。'),
    // ---- 中3 追加 ----
    G(11, 'I have ___ to Hokkaido three times.', 'been', ['gone', 'went', 'go'], '北海道に3回行ったことがあります。'),
    G(11, 'She has ___ in this town since 2015.', 'lived', ['live', 'living', 'lives'], '彼女は2015年からこの町に住んでいます。'),
    G(11, 'Have you ___ your homework yet?', 'done', ['do', 'did', 'doing'], 'もう宿題をしましたか。'),
    G(11, 'I have not seen him ___ last month.', 'since', ['for', 'from', 'ago'], '先月から彼に会っていません。'),
    G(11, 'We have been friends ___ ten years.', 'for', ['since', 'from', 'during'], 'わたしたちは10年間友だちです。'),
    G(11, 'He has ___ left for school.', 'already', ['yet', 'ever', 'never'], '彼はもう学校へ出かけました。'),
    G(11, 'How ___ have you been in Japan?', 'long', ['many', 'often', 'much'], '日本にどのくらいいますか。'),
    G(11, 'It has been ___ since yesterday.', 'snowing', ['snow', 'snowed', 'snows'], 'きのうからずっと雪がふっています。'),
    G(11, 'This room ___ cleaned every day.', 'is', ['has', 'does', 'was being'], 'この部屋は毎日そうじされます。'),
    G(11, 'These cookies ___ made by my sister.', 'were', ['was', 'did', 'have'], 'これらのクッキーは姉（妹）が作りました。'),
    G(11, 'The song is ___ by many people.', 'loved', ['love', 'loving', 'loves'], 'その歌は多くの人に愛されています。'),
    G(11, 'When ___ this bridge built?', 'was', ['did', 'is', 'were'], 'この橋はいつ建てられましたか。'),
    G(11, 'I have a friend ___ speaks three languages.', 'who', ['which', 'whose', 'what'], '3か国語を話す友だちがいます。'),
    G(11, 'This is the picture ___ he painted.', 'which', ['who', 'whose', 'what'], 'これは彼がかいた絵です。'),
    G(11, 'The man ___ you met yesterday is my uncle.', 'that', ['what', 'which', 'whose'], 'きのう会った男性はわたしのおじです。'),
    G(11, 'Look at the dog ___ under the tree.', 'sleeping', ['sleep', 'slept', 'sleeps'], '木の下でねている犬を見て。'),
    G(11, 'This is a car ___ in Germany.', 'made', ['make', 'making', 'makes'], 'これはドイツで作られた車です。'),
    G(11, 'I know ___ she lives.', 'where', ['what', 'which', 'who'], '彼女がどこに住んでいるか知っています。'),
    G(11, 'Please tell me what ___.', 'this is', ['is this', 'this', 'is it'], 'これが何か教えてください。'),
    G(11, 'It is difficult for me ___ early.', 'to get up', ['get up', 'getting up', 'got up'], 'わたしにとって早起きは難しいです。'),
    G(11, 'The box was ___ heavy to carry.', 'too', ['so', 'very', 'enough'], 'その箱は重すぎて運べませんでした。'),
    G(11, 'I asked him ___ me.', 'to help', ['help', 'helping', 'helped'], '彼に手伝ってくれるよう頼みました。'),
    G(11, 'Let me ___ you something.', 'show', ['to show', 'showing', 'showed'], 'あなたにあるものを見せましょう。'),
    G(11, 'The news made us ___.', 'sad', ['sadly', 'sadness', 'to sad'], 'そのニュースはわたしたちを悲しませました。'),
    G(11, 'I helped my mother ___ dinner.', 'cook', ['cooks', 'cooked', 'to cooking'], '母が夕食を作るのを手伝いました。'),
    G(11, 'If I ___ rich, I would buy a big house.', 'were', ['am', 'be', 'will be'], 'もしお金持ちなら、大きな家を買うのに。'),
    G(11, 'I wish I ___ fly like a bird.', 'could', ['can', 'will', 'may'], '鳥のように飛べたらいいのに。'),
    G(11, 'If it ___ sunny, we would go hiking.', 'were', ['is', 'be', 'will be'], '晴れていたら、ハイキングに行くのに。'),
    G(11, 'I know ___ to use this machine.', 'how', ['what', 'that', 'why'], 'この機械の使い方を知っています。'),
    G(11, 'Do you know ___ he is?', 'who', ['what time', 'whose', 'how many'], '彼がだれか知っていますか。'),
  ];

  // ---- 中学の 単語（g: 9=中1, 10=中2, 11=中3） ----
  const W = (g, en, ja) => ({ cat: 'jh', g, en, ja, emoji: '' });
  const words = [
    W(9, 'weekend', '週末'), W(9, 'breakfast', '朝食'), W(9, 'dinner', '夕食'), W(9, 'busy', '忙しい'),
    W(9, 'famous', '有名な'), W(9, 'beautiful', '美しい'), W(9, 'difficult', '難しい'), W(9, 'easy', '簡単な'),
    W(9, 'favorite', 'お気に入りの'), W(9, 'always', 'いつも'), W(9, 'usually', 'たいてい'), W(9, 'sometimes', 'ときどき'),
    W(9, 'often', 'よく・しばしば'), W(9, 'tomorrow', '明日'), W(9, 'yesterday', 'きのう'), W(9, 'answer', '答える'),
    W(9, 'visit', '訪れる'), W(9, 'practice', '練習する'), W(9, 'borrow', '借りる'), W(9, 'wait', '待つ'),
    W(9, 'begin', '始める'), W(9, 'arrive', '到着する'), W(9, 'country', '国'), W(9, 'language', '言語'),
    W(9, 'museum', '博物館'), W(9, 'festival', '祭り'), W(9, 'uncle', 'おじ'), W(9, 'aunt', 'おば'),
    W(10, 'remember', '覚えている'), W(10, 'forget', '忘れる'), W(10, 'decide', '決める'), W(10, 'believe', '信じる'),
    W(10, 'invent', '発明する'), W(10, 'understand', '理解する'), W(10, 'important', '大切な'), W(10, 'dangerous', '危険な'),
    W(10, 'popular', '人気のある'), W(10, 'different', '異なる'), W(10, 'necessary', '必要な'), W(10, 'useful', '役に立つ'),
    W(10, 'culture', '文化'), W(10, 'history', '歴史'), W(10, 'future', '未来'), W(10, 'environment', '環境'),
    W(10, 'experience', '経験'), W(10, 'volunteer', 'ボランティア'), W(10, 'message', '伝言'), W(10, 'information', '情報'),
    W(10, 'carefully', '注意深く'), W(10, 'finally', 'ついに'), W(10, 'suddenly', '突然'), W(10, 'abroad', '海外へ'),
    W(11, 'technology', '科学技術'), W(11, 'society', '社会'), W(11, 'peace', '平和'), W(11, 'war', '戦争'),
    W(11, 'energy', 'エネルギー'), W(11, 'pollution', '汚染'), W(11, 'solve', '解決する'), W(11, 'protect', '守る'),
    W(11, 'reduce', '減らす'), W(11, 'improve', '向上させる'), W(11, 'communicate', '意思を伝え合う'), W(11, 'express', '表現する'),
    W(11, 'respect', '尊敬する'), W(11, 'develop', '発達させる'), W(11, 'discover', '発見する'), W(11, 'although', '〜だけれども'),
    W(11, 'however', 'しかしながら'), W(11, 'instead', '代わりに'), W(11, 'especially', '特に'), W(11, 'probably', 'たぶん'),
    W(11, 'recently', '最近'), W(11, 'whole', '全体の'), W(11, 'foreign', '外国の'), W(11, 'several', 'いくつかの'),

    // ---- 追加の 単語 ----
    W(9, 'classmate', 'クラスメート'), W(9, 'homework', '宿題'), W(9, 'subject', '教科'), W(9, 'club', 'クラブ・部活'),
    W(9, 'library', '図書館'), W(9, 'hospital', '病院'), W(9, 'station', '駅'), W(9, 'restaurant', 'レストラン'),
    W(9, 'morning', '朝'), W(9, 'afternoon', '午後'), W(9, 'evening', '夕方'), W(9, 'night', '夜'),
    W(9, 'early', '早く'), W(9, 'late', 'おそく'), W(9, 'fast', '速い'), W(9, 'slow', 'おそい'),
    W(9, 'open', '開ける'), W(9, 'close', '閉める'), W(9, 'clean', 'そうじする'), W(9, 'wash', '洗う'),
    W(9, 'buy', '買う'), W(9, 'sell', '売る'), W(9, 'carry', '運ぶ'), W(9, 'call', '電話する・呼ぶ'),
    W(9, 'picture', '写真・絵'), W(9, 'present', 'プレゼント'), W(9, 'ticket', 'チケット'), W(9, 'money', 'お金'),
    W(9, 'kind', '親切な'), W(9, 'tired', 'つかれた'), W(9, 'hungry', 'おなかがすいた'), W(9, 'cold', '寒い・かぜ'),
    W(9, 'weather', '天気'), W(9, 'season', '季節'), W(9, 'holiday', '休日'), W(9, 'trip', '旅行'),
    W(10, 'advice', '助言'), W(10, 'chance', '機会'), W(10, 'change', '変える・変化'), W(10, 'choose', '選ぶ'),
    W(10, 'collect', '集める'), W(10, 'continue', '続ける'), W(10, 'cross', '横切る'), W(10, 'enter', '入る'),
    W(10, 'explain', '説明する'), W(10, 'follow', 'ついていく'), W(10, 'grow', '育つ'), W(10, 'guess', '推測する'),
    W(10, 'hold', '持つ・開く'), W(10, 'join', '参加する'), W(10, 'keep', '保つ'), W(10, 'lose', '失う'),
    W(10, 'miss', 'のがす・恋しく思う'), W(10, 'order', '注文する'), W(10, 'plan', '計画'), W(10, 'prepare', '準備する'),
    W(10, 'receive', '受け取る'), W(10, 'return', '帰る・返す'), W(10, 'save', '救う・ためる'), W(10, 'share', '分け合う'),
    W(10, 'cheap', '安い'), W(10, 'expensive', '高価な'), W(10, 'delicious', 'おいしい'), W(10, 'healthy', '健康な'),
    W(10, 'quiet', '静かな'), W(10, 'strange', '奇妙な'), W(10, 'strong', '強い'), W(10, 'weak', '弱い'),
    W(10, 'nature', '自然'), W(10, 'health', '健康'), W(10, 'problem', '問題'), W(10, 'reason', '理由'),
    W(11, 'accident', '事故'), W(11, 'disaster', '災害'), W(11, 'earthquake', '地震'), W(11, 'government', '政府'),
    W(11, 'opinion', '意見'), W(11, 'purpose', '目的'), W(11, 'result', '結果'), W(11, 'situation', '状況'),
    W(11, 'achieve', '達成する'), W(11, 'allow', '許す'), W(11, 'avoid', 'さける'), W(11, 'create', '作り出す'),
    W(11, 'depend', 'たよる'), W(11, 'encourage', 'はげます'), W(11, 'imagine', '想像する'), W(11, 'increase', '増える'),
    W(11, 'influence', '影響'), W(11, 'notice', '気づく'), W(11, 'realize', '気づく・実現する'), W(11, 'recommend', 'すすめる'),
    W(11, 'support', '支える'), W(11, 'survive', '生き残る'), W(11, 'treat', 'あつかう'), W(11, 'waste', 'むだにする'),
    W(11, 'ancient', '古代の'), W(11, 'common', 'ふつうの・共通の'), W(11, 'effective', '効果的な'), W(11, 'global', '世界的な'),
    W(11, 'local', '地元の'), W(11, 'modern', '現代の'), W(11, 'natural', '自然の'), W(11, 'traditional', '伝統的な'),
    W(11, 'actually', '実は'), W(11, 'certainly', '確かに'), W(11, 'immediately', 'すぐに'), W(11, 'unfortunately', '残念ながら'),
  ];
  // 小学校の 単語リストに 足す
  if (window.STUDY_DATA) window.STUDY_DATA.words.push(...words);

  return { grammar, words };
})();
